# Generated by Django 2.0.5 on 2018-05-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='is_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='video',
            name='themes',
        ),
        migrations.AddField(
            model_name='video',
            name='themes',
            field=models.ManyToManyField(related_name='videos_themes', to='core.Theme'),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
