# Generated by Django 2.0.5 on 2018-05-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180521_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
