# Generated by Django 2.0.5 on 2018-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_theme_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='scores',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
