# Generated by Django 2.0.5 on 2018-05-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video_scores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='scores',
            new_name='points',
        ),
    ]
