# Generated by Django 2.0.5 on 2018-05-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180521_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
