# Generated by Django 2.0.5 on 2018-05-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180521_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
