# Generated by Django 2.0.5 on 2018-05-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180521_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
