# Generated by Django 2.0.5 on 2018-05-21 22:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180521_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_uploaded',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2017, 5, 21))]),
        ),
    ]
