# Generated by Django 2.0.5 on 2018-05-22 03:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180521_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_uploaded',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2017, 5, 22))]),
        ),
        migrations.AlterField(
            model_name='video',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
